# Generated by Django 3.2.2 on 2021-05-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='updated_ad',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
